// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gjfpijfhqablzmangpft.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdqZnBpamZocWFibHptYW5ncGZ0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQxMTM1MTEsImV4cCI6MjA4OTY4OTUxMX0.61rH8-UtlN9qrZgPCU0PHIncDm39EO_sWis9o9GbE4U";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});